name: animezone
description: "Your Ultimate Anime Hub."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  flutter_riverpod: ^2.4.10
  equatable: ^2.0.5
  riverpod_annotation:
  cached_network_image: ^3.3.1
  vector_math: ^2.1.4
  intl: ^0.19.0
  image_network: ^2.5.6
  auto_size_text: ^3.0.0
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  riverpod_generator:
  riverpod_lint:
  custom_lint:
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


  fonts:
    - family: ReggaeOne
      fonts:
        - asset: assets/fonts/ReggaeOne-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700